sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran

install:
  - pip install pathlib
  - pip install scipy
  - pip install -r test_requirements.txt

before_script:
  - ./bin/build_model

script:
  - ./bin/test pep8 cov

after_success:
  - codecov