sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.0.5-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - pip install -r test_requirements.txt

before_script:
  - ./bin/build_model

script:
  - ./bin/test pep8 cov

after_success:
  - codecov
