version: '0.0.{build}'

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - TARGET_ARCH: "x64"
      CONDA_PY: "34"
      PY_CONDITION: "python >=3.4,<3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda34-x64"

    - TARGET_ARCH: "x64"
      CONDA_PY: "35"
      PY_CONDITION: "python >=3.5,<3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"

    - TARGET_ARCH: "x64"
      CONDA_PY: "36"
      PY_CONDITION: "python >=3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

platform:
    - x64

install:
    # Remove cygwin (and therefore the git that comes with it).
    - cmd: rmdir C:\cygwin /s /q

    # Use the pre-installed Miniconda for the desired arch
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --set show_channel_urls true
    - cmd: conda update --yes --quiet conda
    - cmd: conda install --file requirements.txt

# Skip .NET project specific build phase.
build: off

build_script:
    - cmd: "%PYTHON%" setup.py install --single-version-externally-managed --record=record.txt
    - cmd: "%PYTHON%" .\bin\build_model -m mingw32-make.exe all STATIC_FLAG=-static
